### ISSUE TITLE
Binaries will not run. Exits with "Trace/BPT trap: 5"

### ISSUE THREAD

**Issue by brettalton** [benvium/libimobiledevice-macosx#1]
I installed the binaries as directed but I can't get them to run. Am I doing something wrong? I'm on OS X 10.8.2

Brett-Alton:libimobiledevice studiospare$ vim ~/.bash_profile
Brett-Alton:libimobiledevice studiospare$ source ~/.bash_profile
Brett-Alton:libimobiledevice studiospare$ idevicesyslog
-bash: idevicesyslog: command not found
Brett-Alton:libimobiledevice studiospare$ idevicescreenshot
-bash: idevicescreenshot: command not found
Brett-Alton:libimobiledevice studiospare$ ./idevicesyslog
dyld: Library not loaded: @executable_path/../lib/libimobiledevice.3.dylib
  Referenced from: /Users/studiospare/Desktop/libimobiledevice/./idevicesyslog
  Reason: image not found
Trace/BPT trap: 5
Brett-Alton:libimobiledevice studiospare$ ./idevicesyslog
dyld: Library not loaded: @executable_path/../lib/libimobiledevice.3.dylib
  Referenced from: /Users/studiospare/Desktop/libimobiledevice/./idevicesyslog
  Reason: image not found
Trace/BPT trap: 5
Brett-Alton:libimobiledevice studiospare$ ./idevicescreenshot
dyld: Library not loaded: @executable_path/../lib/libimobiledevice.3.dylib
  Referenced from: /Users/studiospare/Desktop/libimobiledevice/./idevicescreenshot
  Reason: image not found
Trace/BPT trap: 5

**Comment by benvium** [comment]
I'm using Mac OSX 10.8.2 as well so it's certainly possible to get it to work.

In my .bash_profile I have:

export DYLD_LIBRARY_PATH=/Users/ben/github/libimobiledevice-macosx:$DYLD_LIBRARY_PATH

.. and in the /Users/ben/github/libimobiledevice-macosx folder I have idevicesyslog and the other files in this repo.

Where do you have the executables?

**Comment by ghost** [comment]
Hi I'm using Mac OSX 10.8.2. After I installed it, I can't use idvicescreenshot (I connect my IPad), it shows " Could not connect to screenshotr!" but others are fine.
Am I do something wrong?

**Comment by perqa** [comment]
Same problem as brettalton but I'm on OSX 10.7.5.
 ~/Utilities/benvium-libimobiledevice-macosx-45d8ece/idevicesyslog 
dyld: Library not loaded: @executable_path/../lib/libimobiledevice.3.dylib
  Referenced from: /Users/per/Utilities/benvium-libimobiledevice-macosx-45d8ece/idevicesyslog
  Reason: image not found
Trace/BPT trap: 5

**Comment by rustybrick** [comment]
Have you figured out how to get libimobiledevice running on OS X?

**Comment by benvium** [comment]
If you have trouble can you post the relevant parts of your .bash_profile? It works for me on 10.8.3, I use idevicescreenshot, idevicesyslog, and ideviceinstaller most days.

**Comment by rustybrick** [comment]
I stand corrected.  Retried everything and it works great.  I now get an error when using idevicebackup2 "Could not perform backup protocol version exchange, error code -1"  Seems that I need to get a newer build.  I tried to build from source on my mac and it failed on the same error as the comment on http://blog.boceto.fr/2012/05/05/libimobiledevice-for-macosx/: No package ‘libusbmuxd’ found

Any ideas?  I am looking to get this working as an XCode project, not command line.  Need to run a backup on the active iPhone connected to the computer.

**Comment by benvium** [comment]
Great stuff. I'm afraid I've never tried the idevicebackup2 part, so I'm not terribly surprised is doesn't work.

**Comment by benvium** [comment]
I'm going to close this issue - if you still have trouble @rustybrick you can open a new issue for the specific backup problem.
