### ISSUE TITLE
Can not use idvicescreenshot

### ISSUE THREAD

**Issue by ghost** [benvium/libimobiledevice-macosx#2]
Hi I'm using Mac OSX 10.8.2. After I installed it, I can't use idvicescreenshot (I connect my IPad), it shows " Could not connect to screenshotr!" but others are fine.
Am I do something wrong?

**Comment by aimofankit** [comment]
Hi The problem here is with os version, idevicescreeshot api is not working on iphone/ipad with 6 n above, with ios5 it's working fine. Please provide the solution/fix for the same as early as possible.

**Comment by benvium** [comment]
Hi all. Yes, it does appear that iOS6 locks down security rather more than iOS5 did. idevicescreenshot is no longer working. idevicesyslog still works.  If the authors of this library find a solution (I just compiled it) I'll update the binaries on here.

**Comment by ghost** [comment]
So this one use libimobiledevice-1.1.4. or 1.1.2?

**Comment by benvium** [comment]
oh, it looks like they may have fixed it in the latest version: http://cgit.sukimashita.com/libimobiledevice.git/commit/?id=6fdf7932c946d48157929b37b2956cae19d80ac4 (1.1.4). I'll update the binaries when I get a chance.

**Comment by ghost** [comment]
That's great, many thanks

**Comment by aimofankit** [comment]
Osm benvium, ven can v expect the new binaries or new build released for the same.

**Comment by benvium** [comment]
Unfortunately, I'm having trouble getting the compile to work on Mountain Lion, so I'm not sure yet. Sorry

**Comment by aimofankit** [comment]
Ohk, in that case is it possible for you to build on lower version of MAC os which binary files can be made. Else let me know the procedure I can try creating it.

**Comment by eAi** [comment]
I've produced a patched version that works with iOS 6:

https://github.com/eAi/bits-and-pieces

I produced this by disassembling and manually patching benvium's version. Just overwrite his binaries with mine.

**Comment by benvium** [comment]
Hey that's great. Do you mind if I work them into this repository? Thanks for doing that.

**Comment by eAi** [comment]
Sure - go ahead :)

**Comment by benvium** [comment]
I've updated the repo now and can confirm that idevicescreenshot now works on iOS 6. Thanks eAi!
