### ISSUE TITLE
libimbiledevice compile error at commit 6370bf5

### ISSUE THREAD

**Issue by yeahren** [benvium/libimobiledevice-macosx#3]
Hi @benvium,
i also wanna to compile the libimobiledevice under mac os x 10.8.2 , i have installed libusb 1.0.0 and libusbmuxd 1.0.8 but the libimobiledevice configure process is showing me that:

...
checking how to hardcode library paths into programs... immediate
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libusbmuxd... no
configure: error: Package requirements (libusbmuxd >= 1.0.8) were not met:

No package 'libusbmuxd' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libusbmuxd_CFLAGS
and libusbmuxd_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details

any idea?

**Comment by yeahren** [comment]
Hi 梁威，

Thank you for your reply, i think it is not the reason i met, apt-config wrong path setting cause this issue, anyway i have fixed up this issue and found it is to be nice using homebrew to compile this libiary :)

Peter

**Comment by mihirpmehta** [comment]
Where I can find libusbmuxd package for mac ?

**Comment by Thireus** [comment]
Use instead:

    ./autogen.sh libusbmuxd_LIBS="-L/usr/local/lib -lusbmuxd" libusbmuxd_CFLAGS="-I/usr/local/include"

libusbmuxd is at https://github.com/libimobiledevice/libusbmuxd
