### ISSUE TITLE
how to compile idevicescreenshot for macosx

### ISSUE THREAD

**Issue by JerryGinger** [benvium/libimobiledevice-macosx#4]
Hi @benvium,
As i wanna to export a jpeg file of screenshot of iphone 5, so i recompiled the "idevicescreenshot.c" file using your compiled dynamic library--libimobiledevice.3.dylib. 

Unfortunately, the objective file of idevicescreenshot can not run and gives the errors as follows:
Bus error:10

My development environment is below:
1. Xcode 4.5.2
2 Mac OS X 10.8.2

Looking forward to your early reply. Many thanks.

Best Regards

**Comment by benvium** [comment]
Hi I don't think I know how to help with that one, sorry. I tend to use idevicescreenshot to get the TIFF and then convert with an imagemagick command to png.
—

**Comment by JerryGinger** [comment]
Hi @benvium, 
Thank you for your prompt response. Could you please tell me the way you compile the idevicescreenshot tool? I have just compared your idevicescreenshot version with mine, and the only difference between them I found is their dependency:

your version--->
appletekiMacBook-Pro:libimobiledevice-macosx jerry$ otool -L idevicescreenshot 
idevicescreenshot:
    @executable_path/../lib/libimobiledevice.3.dylib (compatibility version 4.0.0, current version 4.1.0)
    @executable_path/../lib/libplist.1.dylib (compatibility version 1.0.0, current version 1.1.8)
    @executable_path/../lib/libusbmuxd.2.dylib (compatibility version 2.0.0, current version 1.0.8)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.3.11)
    /usr/lib/libssl.0.9.7.dylib (compatibility version 0.9.7, current version 0.9.7)
    /usr/lib/libcrypto.0.9.7.dylib (compatibility version 0.9.7, current version 0.9.7)
    /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)

my version -->
appletekiMacBook-Pro:libimobiledevice-macosx jerry$ otool -L screenshot
screenshot:
    /home/benoit/workspace/imobiledevice/binary/mac/lib/libimobiledevice.3.dylib (compatibility version 4.0.0, current version 4.1.0)
    /home/benoit/workspace/imobiledevice/libplist/build/src/libplist.1.dylib (compatibility version 1.0.0, current version 1.1.8)
    /home/benoit/workspace/imobiledevice/usbmuxd/build/libusbmuxd/libusbmuxd.2.dylib (compatibility version 2.0.0, current version 1.0.8)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)

**Comment by benvium** [comment]
Actually I didn't compile that one, check the link in the README and there's more details on that blog.
—

**Comment by JerryGinger** [comment]
Thank you. I have already compiled libimobiledevice  for Mac OS X ( x86_64 version) successfully and no patch needed.
